"""Add verification_code to User

Revision ID: 820fd9c0356c
Revises: 7083ba86c880
Create Date: 2025-07-04 23:56:24.866715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '820fd9c0356c'
down_revision = '7083ba86c880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_code', sa.String(length=6), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verification_code')

    # ### end Alembic commands ###
