"""Add verification_code and sent_at to users

Revision ID: 60c622785263
Revises: 820fd9c0356c
Create Date: 2025-07-05 00:02:23.642684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60c622785263'
down_revision = '820fd9c0356c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_code_sent_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_verification_code'), ['verification_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_verification_code'))
        batch_op.drop_column('verification_code_sent_at')

    # ### end Alembic commands ###
