"""Updated models with payments improvements

Revision ID: 171a347ab2cd
Revises: 9ad1f531c6e0
Create Date: 2025-07-07 20:52:33.043390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '171a347ab2cd'
down_revision = '9ad1f531c6e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mpesa_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mpesa_payments_transaction_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mpesa_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mpesa_payments_transaction_id'), ['transaction_id'], unique=False)

    # ### end Alembic commands ###
