"""Add received field to orders

Revision ID: 9ec636dc07dc
Revises: cfdc9d32ae36
Create Date: 2025-07-04 16:29:19.003726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ec636dc07dc'
down_revision = 'cfdc9d32ae36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('received', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('received')

    # ### end Alembic commands ###
