"""Add is_password_reset_pending to User

Revision ID: d91e4513d079
Revises: 171a347ab2cd
Create Date: 2025-07-08 01:10:55.246342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd91e4513d079'
down_revision = '171a347ab2cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_password_reset_pending', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_password_reset_pending')

    # ### end Alembic commands ###
