"""empty message

Revision ID: 14aba11bc239
Revises: 9ec636dc07dc
Create Date: 2025-07-04 17:01:22.440668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14aba11bc239'
down_revision = '9ec636dc07dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_confirmed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('admin_confirmed', sa.Boolean(), nullable=True))
        batch_op.drop_column('received')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('received', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('admin_confirmed')
        batch_op.drop_column('user_confirmed')

    # ### end Alembic commands ###
