"""Add force_logout field to users

Revision ID: c839e3ada549
Revises: f05129bd68e5
Create Date: 2025-07-08 08:55:31.162526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c839e3ada549'
down_revision = 'f05129bd68e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('force_logout', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('force_logout')

    # ### end Alembic commands ###
